[package]
name = "lip"
version = "0.1.0"
authors = ["Kevin Li <kevinli020508@gmail.com>"]
edition = "2018"
description = "Lip provides powerful parser combinators for creating reusable and flexible parsers."
keywords = ["parser", "combinator", "functional"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
im = "14.3.0"